# -*- coding: utf-8 -*-
from . import img_file_upload
from . import product_product
from . import product_template
from . import res_partner
from . import sale_order
from . import sale_order_line
from . import setu_generic_product_image
from . import setu_multi_ecommerce_connector
from . import setu_process_history
from . import setu_process_history_line
from . import setu_ecommerce_customer_chain
from . import setu_ecommerce_customer_chain_line
from . import setu_ecommerce_order_chain
from . import setu_ecommerce_order_chain_line
from . import setu_woocommerce_order_notes
from . import setu_woocommerce_coupon_chain
from . import setu_woocommerce_coupon_chain_line
from . import setu_woocommerce_coupons
from . import setu_woocommerce_order_status
from . import setu_woocommerce_payment_gateway
from . import setu_ecommerce_product_chain
from . import setu_ecommerce_product_chain_line
from . import setu_woocommerce_product_category
from . import setu_woocommerce_product_image
from . import setu_woocommerce_product_tags
from . import setu_woocommerce_product_attributes
from . import setu_woocommerce_product_attribute_terms
from . import setu_woocommerce_product_template
from . import setu_woocommerce_product_variant
from . import setu_woocommerce_sale_process_configuration
from . import setu_woocommerce_webhook
from . import stock_picking
from . import delivery_carrier
from . import account_move
